name: energyadventure
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  confetti: ^0.7.0
  connectivity_plus: ^6.0.4
  dio: ^5.5.0+1
  equatable: ^2.0.5
  flame: ^1.18.0
  flame_audio: ^2.10.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  
  assets:
    - assets/data/provitional_questions.json
    - assets/images/
    - assets/images/
    - assets/images/menu/
    - assets/images/tutorials/flappy/
    - assets/images/games/flappy/
    - assets/images/games/questions/
    - assets/audio/

  fonts:
    - family: Game
      fonts:
        - asset: assets/fonts/Game.ttf
